title: Hacker-Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "SomeHacker"
  email: "someone@somewebsite.somedomain"
  url: "webpwners.github.io"

baseurl: /

header_pages:
  - index.html
  - peter.md
  - about.md
  - contact.md

style: hacker

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

theme: jekyll-theme-cayman

... 
layout: default
comments: true
# other options
...
